---

- name: Set A Record mail
  cloudflare_dns:
    account_api_token: "{{ cloudflare_api.stdout }}"
    account_email: "{{ cloudflare_email.stdout }}"
    zone: "{{ domain.stdout }}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ public_ip }}"
    record: "mail"

- name: 'Register DKIM'
  shell: cat /mnt/docker/mail/dkim/{{ domain.stdout }}/public.key | sed -n '2p' | cut -c3- | tr -d ';)"'
  register: dkim
  ignore_errors: True

- name: Set DKIM Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare_api.stdout }}"
    account_email: "{{ cloudflare_email.stdout }}"
    zone: "{{ domain.stdout }}"
    state: present
    solo: true
    proxied: no
    type: TXT
    value: "v=DKIM1; k=rsa; {{ dkim.stdout }}"
    record: "mail._domainkey"

- name: Set MX Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare_api.stdout }}"
    account_email: "{{ cloudflare_email.stdout }}"
    zone: "{{ domain.stdout }}"
    state: present
    solo: true
    proxied: no
    priority: 10
    type: MX
    value: "mail.{{ domain.stdout }}"
    record: "@"

- name: Set SPF Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare_api.stdout }}"
    account_email: "{{ cloudflare_email.stdout }}"
    zone: "{{ domain.stdout }}"
    state: present
    solo: true
    proxied: no
    type: TXT
    value: "v=spf1 a mx ip4:{{ public_ip }} ~all"
    record: "@"

- name: Set DMARC Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare_api.stdout }}"
    account_email: "{{ cloudflare_email.stdout }}"
    zone: "{{ domain.stdout }}"
    state: present
    solo: true
    proxied: no
    type: TXT
    value: "v=DMARC1; p=reject; rua=mailto:postmaster@{{ domain.stdout }}; ruf=mailto:admin@{{ domain.stdout }}; adkim=s;aspf=s; pct=100; rf=afrf; sp=reject"
    record: "_dmarc"