---

# LABELS ######################################################################
- name: 'Ajout label traefik'
  set_fact:
    pg_labels:
      traefik.enable: 'true'
      ## HTTP Routers
      traefik.http.routers.spam-rtr.entrypoints: 'https'
      traefik.http.routers.spam-rtr.rule: 'Host(`spam.{{user.domain}}`)'
      traefik.http.routers.spam-rtr.tls: 'true'
      ## Middlewares
      #traefik.http.routers.spam-rtr.middlewares: "{{ 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
      ## HTTP Services
      traefik.http.routers.spam-rtr.service: 'spam-svc'
      traefik.http.services.spam-svc.loadbalancer.server.port: '11334'

- name: 'Deploying mailserver'
  docker_container:
    domainname: '{{user.domain}}'
    name: 'mailserver'
    recreate: true
    image: 'hardware/mailserver:1.1-stable'
    hostname: 'mail'
    pull: yes
    published_ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - '/mnt/docker/mail:/var/mail'
#      - '/opt/seedbox/docker/traefik/acme:/etc/letsencrypt/acme'
    env:
      DBPASS: '{{user.pass}}'
      RSPAMD_PASSWORD: '{{user.pass}}'
    restart_policy: unless-stopped
    networks:
      - name: mail_network
      - name: traefik_proxy
    state: started
    labels: '{{pg_labels}}'




