---

# LABELS ######################################################################
- name: 'Ajout label traefik'
  set_fact:
    pg_labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:spam.{{domain.stdout}}'
      traefik.port: '11334'
      traefik.docker.network: 'traefik_proxy'

- name: 'Deploying mailserver'
  docker_container:
    domainname: '{{domain.stdout}}'
    name: 'mailserver'
    recreate: true
    image: 'hardware/mailserver:1.1-stable'
    hostname: 'mail'
    pull: yes
    published_ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - '/mnt/docker/mail:/var/mail'
      - '/opt/seedbox/docker/traefik/acme:/etc/letsencrypt/acme'
    env:
      DBPASS: '{{pass.stdout}}'
      RSPAMD_PASSWORD: '{{pass.stdout}}'
    restart_policy: unless-stopped
    networks:
      - name: mail_network
      - name: traefik_proxy
    state: started
    labels: '{{pg_labels}}'




