---

# LABELS ######################################################################
- name: 'Ajout label traefik'
  set_fact:
    pg_labels:
      traefik.enable: 'true'
      ## HTTP Routers
      traefik.http.routers.postfixadmin-rtr.entrypoints: 'https'
      traefik.http.routers.postfixadmin-rtr.rule: 'Host(`postfixadmin.{{user.domain}}`)'
      traefik.http.routers.postfixadmin-rtr.tls: 'true'
      ## Middlewares
      traefik.http.routers.postfixadmin-rtr.middlewares: "{{ 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
      ## HTTP Services
      traefik.http.routers.postfixadmin-rtr.service: 'postfixadmin-svc'
      traefik.http.services.postfixadmin-svc.loadbalancer.server.port: '8888'


- name: 'Deploying postfixadmin'
  docker_container:
    name: 'postfixadmin'
    recreate: true
    domainname: '{{user.domain}}'
    hostname: 'mail'
    image: 'hardware/postfixadmin'
    pull: yes
    env:
      DBPASS: '{{user.pass}}'
    restart_policy: unless-stopped
    networks:
      - name: mail_network
      - name: traefik_proxy
    state: started
    labels: '{{pg_labels}}'


