---

# LABELS ######################################################################
- name: 'Ajout label traefik'
  set_fact:
    pg_labels:
      traefik.enable: 'true'
      traefik.frontend.rule: 'Host:postfixadmin.{{user.domain}}'
      traefik.port: '8888'

- name: 'Deploying postfixadmin'
  docker_container:
    name: 'postfixadmin'
    recreate: true
    domainname: '{{user.domain}}'
    hostname: 'mail'
    image: 'hardware/postfixadmin'
    pull: yes
    env:
      DBPASS: '{{user.pass}}'
    restart_policy: unless-stopped
    networks:
      - name: mail_network
      - name: traefik_proxy
    state: started
    labels: '{{pg_labels}}'


