---

# LABELS ######################################################################
- name: 'Ajout label traefik'
  set_fact:
    pg_labels:
      traefik.enable: 'true'
      ## HTTP Routers
      traefik.http.routers.webmail-rtr.entrypoints: 'https'
      traefik.http.routers.webmail-rtr.rule: 'Host(`webmail.{{user.domain}}`)'
      traefik.http.routers.webmail-rtr.tls: 'true'
      ## Middlewares
      traefik.http.routers.webmail-rtr.middlewares: "{{ 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
      ## HTTP Services
      traefik.http.routers.webmail-rtr.service: 'webmail-svc'
      traefik.http.services.webmail-svc.loadbalancer.server.port: '8888'

- name: 'Deploying rainloop'
  docker_container:
    name: 'rainloop'
    recreate: true
    image: 'hardware/rainloop'
    pull: yes
    volumes:
      - '/mnt/docker/rainloop:/rainloop/data'
    restart_policy: unless-stopped
    networks:
      - name: mail_network
      - name: traefik_proxy
    state: started
    labels: '{{pg_labels}}'


