#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: deluge
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'deluge'
        intport: '8112'
        image: 'linuxserver/deluge'

    - name: 'Creating rutorrent folder paths'
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/home/{{user.name}}/local/{{pgrole}}'
        - '/home/{{user.name}}/local/{{pgrole}}/downloads'
        - '/home/{{user.name}}/local/{{pgrole}}/incomplete'
        - '/home/{{user.name}}/local/{{pgrole}}/torrent'
        - '/home/{{user.name}}/local/{{pgrole}}/watch'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{user.domain}}'
          traefik.frontend.auth.basic.users: '{{ user.htpwd if not (oauth_enabled) | default(false) else omit }}'
          traefik.frontend.headers.SSLHost: '{{pgrole}}.{{user.domain}}'
          traefik.docker.network: 'traefik_proxy'
          traefik.frontend.passHostHeader: 'true'
          traefik.frontend.headers.SSLForceHost: 'true'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.auth.forward.address: 'http://oauth:4181'
          traefik.frontend.auth.forward.authResponseHeaders: 'X-Forwarded-User'
          traefik.frontend.auth.forward.trustForwardHeader: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}:/config'
          - '/home/{{user.name}}:/home/{{user.name}}'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{user.userid}}'
          PGID: '{{user.groupid}}'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '127.0.0.1:8112:8112'
          - '127.0.0.1:58112:58112'
          - '127.0.0.1:58846:58846'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ###########################################################
    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        timeout: 10

    - name: Stopping {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    - name: 'Checking for appdata'
      wait_for:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/core.conf'
        state: present
        delay: 5

    - name: Set move completed location
      lineinfile:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/core.conf'
        regexp: '"move_completed_path".*'
        line: '"move_completed_path": "/home/{{user.name}}/local/{{pgrole}}/downloads",'
        state: present

    - name: Set download location
      lineinfile:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/core.conf'
        regexp: '"download_location".*'
        line: '"download_location": "/home/{{user.name}}/local/{{pgrole}}/incomplete",'
        state: present

    - name: Setting torrent file directory
      lineinfile:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/core.conf'
        regexp: '"torrentfiles_location".*'
        line: '"torrentfiles_location": "/home/{{user.name}}/local/{{pgrole}}/torrent",'
        state: present

    - name: Setting torrent watch directory
      lineinfile:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/core.conf'
        regexp: '"autoadd_location".*'
        line: '"autoadd_location": "/home/{{user.name}}/local/{{pgrole}}/watch",'
        state: present

    - name: Setting move_completed
      lineinfile:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/core.conf'
        regexp: '"move_completed".*'
        line: '"move_completed": true,'
        state: present

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started
