---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ settings.source }}/includes/dockerapps/templates/generique/generique.yml"

  tasks:

    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'dmm'
        intport: '3000'

    - name: Checking for existing app data
      stat:
        path: '{{ settings.storage }}/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Set DNS Record on CloudFlare"
      include_tasks: "{{ settings.source }}/includes/config/roles/cloudflare/tasks/main.yml"
      vars:
        subdomain: "{{sub[pgrole][pgrole] if sub_enabled else pgrole}}"
      when: cloudflare_enabled

    - name: Create service file
      become: yes
      template:
        dest: "{{ settings.storage }}/vars/dmm.yml"
        src: "{{ settings.source }}/includes/dockerapps/templates/dmm/dmm.yml.j2"

    - name: Create service file
      become: yes
      template:
        dest: "{{ settings.storage }}/vars/.env.local"
        src: "{{ settings.source }}/includes/dockerapps/templates/dmm/.env.local.yml.j2"

    - name: deploy Docker Compose stack
      command: docker compose -f "{{ settings.storage }}/vars/dmm.yml" up -d

    - name: Remove a file, if present
      file:
        path: "{{ settings.storage }}/vars/.env.local"
        state: absent

    - name: Remove a file, if present
      file:
        path: "{{ settings.storage }}/vars/dmm.yml"
        state: absent