---
- hosts: localhost
  gather_facts: false
  vars_files:
  - /opt/seedbox/variables/account.yml
  tasks:
  - name: launch glftpd
    docker_container:
      image: jonarin/glftpd
      name: glftpd
      network_mode: host
      env:
        GL_PORT: "1337"
        TZ: "Europe/Paris"
      state: started
      restart_policy: unless-stopped
      volumes:
      - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/config:/glftpd/site:rw"
      - "{{ lookup('env','HOME') }}:/glftpd/ftp-data"
      - '/etc/localtime:/etc/localtime:ro'