---
# https://github.com/Kometa-Team/ImageMaid

- hosts: localhost
  gather_facts: false
  tasks:

    - name: Creating paths
      become: yes
      file: "path={{item}} state=directory mode=0775 owner={{ lookup('env','MYUID') }} group={{ lookup('env','MYGID') }}"
      with_items:
        - "{{ settings.storage }}/docker/{{ lookup('env','USER') }}/imagmaid"
        - "{{ settings.storage }}/docker/{{ lookup('env','USER') }}/imagmaid/config"
        - "{{ settings.storage }}/docker/{{ lookup('env','USER') }}/plex/plex"

    - name: fichier .env
      template:
        dest: "{{ settings.storage }}/docker/{{ lookup('env', 'USER') }}/imagmaid/config/{{ item.dest }}"
        src: "{{ settings.source }}/includes/dockerapps/templates/imagmaid/{{ item.src }}"
      with_items:
        - { dest: ".env", src: ".env.j2" }
      become: yes
      become_user: "{{ lookup('env', 'USER') }}"
      
    - name: Create a data container
      community.docker.docker_container:
        name: imagmaid
        image: meisnate12/plex-image-cleanup
        user: "{{ lookup('env','MYUID') }}:{{ lookup('env','MYGID') }}"
        volumes:
          - "{{ settings.storage }}/docker/{{ lookup('env','USER') }}/imagmaid/config:/config"
          - "{{ settings.storage }}/docker/{{ lookup('env','USER') }}/plex:/plex"
        env:
          TZ: "Europe/Paris"
        networks:
          - name: traefik_proxy

