#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    # VARIABLES ############################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'
      
    # FACTS #######################################################################

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: jackett
      when: cloudflare_config.stat.exists

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'jackett'
        intport: '9117'
        image: 'linuxserver/jackett'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}'

    # MIGRATIONS (MANDATORY) ############################################################
    - name: Checking for old app data
      stat:
        path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/Jackett/ServerConfig.json'
      register: olddatacheck

    - name: Migrating appdata
      shell: 'mv /opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/Jackett/* /opt/seedbox/docker/{{user.stdout}}/{{pgrole}}'
      ignore_errors: yes
      when: olddatacheck.stat.exists

    - name: Migrating appdata
      shell: 'rmdir /opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/Jackett'
      ignore_errors: yes
      when: olddatacheck.stat.exists

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/ServerConfig.json'
      register: datacheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.auth.basic: '{{passwd.stdout}}' 
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}:/config/Jackett'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{userid.stdout}}'
          PGID: '{{groupid.stdout}}'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ####################################################
    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/ServerConfig.json'
        state: present
        msg: ServerConfig.json creation failed

    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started
