#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
  
    # VARIABLES ############################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'
      
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'jellyfin'
        intport: '8096'
        extport: '9096'
        image: 'jellyfin/jellyfin:latest'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}'

    - name: 'XML Check'
      stat:
        path: /opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/config/system.xml
      register: xmlcheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.headers.frameDeny: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}:/config'
          - '/home/{{user.stdout}}/Medias:/home/{{user.stdout}}/Medias'
          - '/var/run/docker.sock:/var/run/docker.sock'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          GIDLIST: '{{groupid.stdout}}'
          PUID: '{{userid.stdout}}'
          PGID: '{{groupid.stdout}}'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        user: {{userid.stdout}}:{{groupid.stdout}}
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        expose: '8096'
        state: started
        labels: '{{pg_labels}}'

    # FIRST TIME CONFIGURATION ###########################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:

      - name: 'Pending XML Generation'
        wait_for:
          path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/config/system.xml'
          state: present

      - name: 'Wait 5 Seconds'
        wait_for:
          timeout: 5

      - name: 'Stop {{pgrole}}'
        docker_container:
          name: '{{pgrole}}'
          state: stopped

      - name: 'Turn Off Reporting'
        xml:
          path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/config/system.xml'
          xpath: /ServerConfiguration/EnableAnonymousUsageReporting
          value: 'false'

      - name: 'Restart {{pgrole}}'
        docker_container:
          name: '{{pgrole}}'
          state: started
      when: not xmlcheck.stat.exists
