#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
# CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: "medusa"
        intport: "8081"
        extport: "8081"
        image: "linuxserver/medusa"

# LABELS #### KEEPS BOTTOM CLEAN ###########################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.%DOMAIN%'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/%USER%/{{pgrole}}:/config'
          - '/etc/localtime:/etc/localtime:ro'
          - '/home/%USER%:/home/%USER%'
          - '/home/%USER%/Medias/%SERIES%:/tv/Series'
          - '/home/%USER%/Medias/%ANIMES%:/tv/Animes'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '%UID%'
          PGID: '%GID%'

    # MAIN SCRIPT ##############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}-%USER%'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'
