#!/bin/bash
---
- hosts: localhost
  gather_facts: false
  roles:
      - kwoodson.yedit
  vars:
    pgrole: 
    pg_dev: []
  vars_files:
    - /opt/seedbox/variables/account.yml
    - "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/generique/generique.yml"
  tasks:

    - name: create netdata state
      shell: |
        echo "1" > /opt/seedbox/status/netdata

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check


    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.netdata.netdata if sub_enabled else 'netdata'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'netdata'
        intport: '19999'
        image: 'netdata/netdata'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.netdata-rtr.entrypoints: 'https'
          traefik.http.routers.netdata-rtr.rule: 'Host(`{{sub.netdata.netdata if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.netdata-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.netdata-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists and sub[pgrole].auth == 'authelia' | default(false)
          else 'chain-basic-auth@file' if auth_enabled and sub[pgrole].auth == 'basique' | default(false)
          else 'chain-oauth@file' if auth_enabled and sub[pgrole].auth == 'oauth' | default(false)
          else omit if auth_enabled and sub[pgrole].auth == 'aucune'}}"
          ## HTTP Services
          traefik.http.routers.netdata-rtr.service: 'netdata-svc'
          traefik.http.services.netdata-svc.loadbalancer.server.port: '8080'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{pgrole}}/netdataconfig:/etc/netdata"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{pgrole}}/netdatalib:/var/lib/netdata"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{pgrole}}/netdatacache:/var/cache/netdata"
          - "/etc/passwd:/host/etc/passwd:ro"
          - "/etc/group:/host/etc/group:ro"
          - "/proc:/host/proc:ro"
          - "/sys:/host/sys:ro"
          - "/etc/os-release:/host/etc/os-release:ro"

    - name: Get physical disks
      shell: "lsblk |grep disk |awk '{print \"/dev/\"$1}'"
      register: mydisks




    - name: debug
      debug:
        msg: "{{ pg_dev}}"

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        capabilities:
          - SYS_PTRACE
        state: started
        labels: '{{pg_labels}}'
        privileged: true

