#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
  
    # VARIABLES ############################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'
      
    # FACTS #######################################################################

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: nextcloud
      when: cloudflare_config.stat.exists

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'nextcloud'
        intport: '443'
        extport: '4645'
        image: 'linuxserver/nextcloud'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.protocol: 'https'
          traefik.enable: 'true'
          traefik.https.port: '443'
          traefik.https.frontend.entryPoints: 'https'
          traefik.https.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/seedbox/docker/{{user.stdout}}/nextcloud/data:/data'
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/conf:/config'
          - '/home/{{user.stdout}}:/home/{{user.stdout}}'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{userid.stdout}}'
          PGID: '{{groupid.stdout}}'

    - name: Create and start nextcloud container
      docker_container:
        name: nextcloud
        image: 'linuxserver/nextcloud'
        pull: yes
        published_ports:
          - '127.0.0.1:4645:443'
        env:
          PUID: '{{userid.stdout}}'
          PGID: '{{groupid.stdout}}'
        volumes: '{{pg_volumes}}'
        networks:
          - name: traefik_proxy
        restart_policy: unless-stopped
        state: started
        labels: '{{pg_labels}}'
