#!/bin/bash
---
- hosts: localhost
  gather_facts: false
  vars:
    pgrole: ntopngsys
  vars_files:
    - /opt/seedbox/variables/account.yml
    - "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/generique/generique.yml"
  tasks:

    - name: create ntopngsys state
      shell: |
        echo "1" > /opt/seedbox/status/ntopngsys

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ntopngsys'
        intport: '8080'
        image: 'ghcr.io/linuxserver/ntopngsys'


    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.ntopngsys.ntopngsys if sub_enabled else 'ntopngsys'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ntopngsys'
        intport: '3000'
        image: 'ntop/ntopng:stable'

    - name: Creating paths
      become: yes
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/config"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/data"

    - name: Creating paths with 777
      become: yes
      file:
        path: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/redis"
        state: directory
        mode: 0777
        owner: "{{user.userid}}"
        group: "{{user.groupid}}"

    - name: Fichier toml pour traefik
      template:
        src: "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/{{ pgrole }}/ntopngsys.toml.j2"
        dest: "{{ lookup('env','CONFDIR') }}/docker/traefik/rules/ntopngsys.toml"

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'false'


    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/config:/etc/ntopng"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/data:/var/lib/ntopng"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/redis:/var/lib/redis"

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{user.userid}}'
          PGID: '{{user.groupid}}'
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: host
        state: started
        labels: '{{pg_labels}}'



