#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  tasks:

    # VARIABLES ################################################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'

    - name: 'Register appli'
      shell: 'cat /opt/seedbox/variables/appli'
      register: appli
      ignore_errors: True

    - name: 'Register port'
      shell: 'cat /opt/seedbox/variables/port'
      register: port
      ignore_errors: True

    - name: 'Register image'
      shell: 'cat /opt/seedbox/variables/image'
      register: image
      ignore_errors: True

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: Check config oauth_client exists
      stat:
        path: "/opt/seedbox/variables/oauth_client"
      register: oauth_client

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: 'ntopng'
      when: cloudflare_config.stat.exists

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ntopng'
        intport: '3000'
        image: 'aerya/ntopng:3.8_Ubuntu_16.04'

    - name: 'Creating ntopng folder paths'
      file: 'path={{item}} state=directory mode=0775 owner=999 group=999'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/config'
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/data'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.auth.basic: '{{ passwd.stdout if (not oauth_client.stat.exists) | default(false) else omit }}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.auth.forward.address: 'http://oauth:4181'
          traefik.frontend.auth.forward.authResponseHeaders: 'X-Forwarded-User'
          traefik.frontend.auth.forward.trustForwardHeader: 'true'

###################################### Début de zone à modifier si besoin #######################

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/config:/etc/ntopng'
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/data:/var/lib/ntopng'

##################################### Fin de zone à modifier #####################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'
