#!/bin/bash
---
- hosts: localhost
  gather_facts: false
  vars:
    pgrole: openvpn
  vars_files:
    - /opt/seedbox/variables/account.yml
    - "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/generique/generique.yml"
  tasks:

    - name: create openvpn state
      shell: |
        echo "1" > /opt/seedbox/status/openvpn

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'openvpn'
        intport: '7878'
        image: 'ghcr.io/linuxserver/openvpn-as'


    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.openvpn.openvpn if sub_enabled else 'openvpn'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'openvpn'
        intport: '7878'
        image: 'ghcr.io/linuxserver/openvpn-as'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.openvpn-rtr.entrypoints: 'https'
          traefik.http.routers.openvpn-rtr.rule: 'Host(`{{sub.openvpn.openvpn if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.openvpn-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.openvpn-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists and sub[pgrole].auth == 'authelia' | default(false)
          else 'chain-basic-auth@file' if auth_enabled and sub[pgrole].auth == 'basique' | default(false)
          else 'chain-oauth@file' if auth_enabled and sub[pgrole].auth == 'oauth' | default(false)
          else omit if auth_enabled and sub[pgrole].auth == 'aucune'}}"
          ## HTTP Services
          traefik.http.routers.openvpn-rtr.service: 'openvpn-svc'
          traefik.http.services.openvpn-svc.loadbalancer.server.port: '7878'
          ## TCP Services
          traefik.tcp.routers.openvpn-tcp.entrypoints: 'https'
          traefik.tcp.routers.openvpn-tcp.rule: 'HostSNI(`{{sub.openvpn.openvpn if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.tcp.routers.openvpn-tcp.tls: 'true'
          traefik.tcp.routers.openvpn-tcp.tls.passthrough: 'true'
          traefik.tcp.routers.openvpn-tcp.service: 'openvpn-tcp-svc'
          traefik.tcp.services.openvpn-tcp-svc.loadbalancer.server.port: '943'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - "/opt/seedbox/docker/{{ lookup('env','USER') }}/{{pgrole}}/config:/config"
          - "{{ lookup('env','HOME') }}:{{ lookup('env','HOME') }}"

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{user.userid}}'
          PGID: '{{user.groupid}}'
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        capabilities: NET_ADMIN
        pull: yes
        ports:
          - '943:943'
          - '9443:9443'
          - '1194:1194'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'
