#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'pyload'
        intport: '8000'
        extport: '2938'
        intport2: '7227'
        extport2: '7227'
        image: 'writl/pyload'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner=%UID% group=%GID%'
      with_items:
        - '/opt/seedbox/docker/%USER%/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'

          traefik.frontend.rule: 'Host:{{pgrole}}.%DOMAIN%'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/%USER%/{{pgrole}}:/opt/pyload/pyload-config'
          - '/opt/seedbox/docker/%USER%/{{pgrole}}:/opt/pyload/Downloads'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '%UID%'
          PGID: '%GID%'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}-%USER%'
        pull: yes
        published_ports:
          - '{{extport}}:{{intport}}'
          - '{{extport2}}:{{intport2}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'
