#!/bin/bash
---
- hosts: localhost
  gather_facts: false
  vars:
    pgrole: rutorrent
  vars_files:
    - /opt/seedbox/variables/account.yml
    - "{{ lookup('env','BASEDIR') }}/includes/dockerapps/templates/generique/generique.yml"
  tasks:

    - name: create rutorrent state
      shell: |
        echo "1" > /opt/seedbox/status/rutorrent

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check


    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.rutorrent.rutorrent if sub_enabled else 'rutorrent'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'rutorrent'
        intport: '8080'
        image: 'mondedie/rutorrent:latest'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.rutorrent-rtr.entrypoints: 'https'
          traefik.http.routers.rutorrent-rtr.rule: 'Host(`{{sub.rutorrent.rutorrent if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.rutorrent-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.rutorrent-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists and sub[pgrole].auth == 'authelia' | default(false)
          else 'chain-basic-auth@file' if auth_enabled and sub[pgrole].auth == 'basique' | default(false)
          else 'chain-oauth@file' if auth_enabled and sub[pgrole].auth == 'oauth' | default(false)
          else omit if auth_enabled and sub[pgrole].auth == 'aucune'}}"
          ## HTTP Services
          traefik.http.routers.rutorrent-rtr.service: 'rutorrent-svc'
          traefik.http.services.rutorrent-svc.loadbalancer.server.port: '8080'
          # Pour contourner l'authentification pour des outils de style nzb360, décommentez le pavé ci dessous
          #  traefik.http.routers.rutorrent-rtr-bypass.rule: 'Path(`/RPC2`)'
          #  traefik.http.routers.rutorrent-rtr-bypass.priority: '100'
          #  traefik.http.routers.rutorrent-rtr-bypass.tls: 'true'
          #  traefik.http.routers.rutorrent-rtr-bypass.middlewares: 'chain-basic-auth@file'
          #  traefik.http.routers.rutorrent-rtr-bypass.service: 'rutorrent-svc'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{pgrole}}/config:/config"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{pgrole}}/data:/data"
          - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/{{ pgrole }}/sock:/run/rtorrent"
          - "{{ lookup('env','HOME') }}:{{ lookup('env','HOME') }}"

          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          UID: '{{user.userid}}'
          GID: '{{user.groupid}}'
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        ports:
          - '45000:45000'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'



