#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'sabnzbd'
        intport: '8080'
        extport: '8080'
        image: 'linuxserver/sabnzbd'

    - name: 'Checking for existing app data'
      stat:
        path: /opt/appdata/sabnzbd/sabnzbd.ini
      register: inicheck

    # LABELS ######################################################################

    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.%DOMAIN%'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/seedbox/docker/%USER%/{{pgrole}}:/config'
          - '/home/%USER%/filebot:/downloads'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '%UID%'
          PGID: '%GID%'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}-%USER%'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ###########################################################
    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
        state: present
        delay: 5
        
    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}-%USER%'
        state: stopped

    # FIRST TIME CONFIGURATION ###########################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: Set host_whitelist
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: host_whitelist
            value: 'sabnzbd.%DOMAIN%,'
            state: present

        - name: Set direct_unpack
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: direct_unpack
            value: '1'
            state: present

        - name: Set ignore_samples
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: ignore_samples
            value: '1'
            state: present

        - name: set unwanted_extensions
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: unwanted_extensions
            value: exe, com, bat, sh, iso, m2ts, mt2s
            state: present

        - name: set cleanup_list
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: cleanup_list
            value: nfo, exe, com, bat, txt, doc, xls, xlxs, docx, doc, jpg, jeg, gif, png
            state: present

        - name: set action_on_unwanted_extensions
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: action_on_unwanted_extensions
            value: '2'
            state: present

        - name: set pause_on_pwrar - aborts encrypted rar rather than pausing
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: pause_on_pwrar
            value: '2'
            state: present

        - name: set new_nzb_on_failure - try a new nzb if it fails
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: new_nzb_on_failure
            value: '1'
            state: present

        - name: set flat_unpack
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: flat_unpack
            value: '1'
            state: present

        - name: set download_free
          ini_file:
            path: '/opt/seedbox/docker/%USER%/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: download_free
            value: '25G'
            state: present
      when: not inicheck.stat.exists

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}-%USER%'
        state: started
