#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
  
    # VARIABLES ############################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'
      
    # FACTS #######################################################################

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: Check config oauth_client exists
      stat:
        path: "/opt/seedbox/variables/oauth_client"
      register: oauth_client

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: sabnzbd
      when: cloudflare_config.stat.exists

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'sabnzbd'
        intport: '8080'
        image: 'linuxserver/sabnzbd'

    - name: 'Creating sabnzbd folder paths'
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/home/{{user.stdout}}/local/{{pgrole}}'

    - name: 'Checking for existing app data'
      stat:
        path: /opt/appdata/sabnzbd/sabnzbd.ini
      register: inicheck

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.frontend.auth.basic: '{{ passwd.stdout if (not oauth_client.stat.exists) | default(false) else omit }}'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.auth.forward.address: 'http://oauth:4181'
          traefik.frontend.auth.forward.authResponseHeaders: 'X-Forwarded-User'
          traefik.frontend.auth.forward.trustForwardHeader: 'true'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}:/config'
          - '/home/{{user.stdout}}:/home/{{user.stdout}}'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{userid.stdout}}'
          PGID: '{{groupid.stdout}}'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ###########################################################
    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
        state: present
        delay: 5
        
    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    # FIRST TIME CONFIGURATION ###########################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: Set host_whitelist
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: host_whitelist
            value: 'sabnzbd.{{domain.stdout}},'
            state: present

        - name: Set direct_unpack
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: direct_unpack
            value: '1'
            state: present

        - name: Set ignore_samples
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: ignore_samples
            value: '1'
            state: present

        - name: set unwanted_extensions
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: unwanted_extensions
            value: exe, com, bat, sh, iso, m2ts, mt2s
            state: present

        - name: set cleanup_list
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: cleanup_list
            value: nfo, exe, com, bat, txt, doc, xls, xlxs, docx, doc, jpg, jeg, gif, png
            state: present

        - name: set action_on_unwanted_extensions
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: action_on_unwanted_extensions
            value: '2'
            state: present

        - name: set pause_on_pwrar - aborts encrypted rar rather than pausing
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: pause_on_pwrar
            value: '2'
            state: present

        - name: set new_nzb_on_failure - try a new nzb if it fails
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: new_nzb_on_failure
            value: '1'
            state: present

        - name: set flat_unpack
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: flat_unpack
            value: '1'
            state: present

        - name: set download_free
          ini_file:
            path: '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}/sabnzbd.ini'
            section: misc
            option: download_free
            value: '25G'
            state: present
      when: not inicheck.stat.exists

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started
