#!/bin/bash

- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'sensorr'
        intport: '5070'
        image: 'thcolin/sensorr'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner=%UID% group=%GID% recurse=yes'
      with_items:
        - '/opt/seedbox/docker/%USER%/{{pgrole}}'
        - '/opt/seedbox/docker/%USER%/{{pgrole}}/config'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.%DOMAIN%'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/%USER%/{{pgrole}}/config:/app/sensorr/config'
          - '/home/%USER%:/home/%USER%'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '%UID%'
          PGID: '%GID%'
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}-%USER%'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION #################################################################

    - name: execute command in docker
      shell: |
        docker exec sensorr-%USER% sh -l -c "mv /app/sensorr/config.default.json /app/sensorr/config/config.json"
      register: result

    - debug: msg="{{ result.stdout }}"
