#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'syncthing'
        intport: '8384'
        extport: '8384'
        intport2: '22000'
        extport2: '22000'
        intport3: '21027'
        extport3: '21027'
        image: 'linuxserver/syncthing'

    # EXTRA FOR RUTORRENT #########################################################
    - name: 'Create {{pgrole}} script directories'
      file: 'path={{item}} state=directory mode=0775 owner=%UID% group=%GID% recurse=yes'
      with_items:
        - '/opt/seedbox/docker/%USER%/{{pgrole}}'
        - '/opt/seedbox/docker/%USER%/{{pgrole}}/sync'
        - '/opt/seedbox/docker/%USER%/{{pgrole}}/config'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.%DOMAIN%'
          traefik.frontend.auth.basic: '%VAR%'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/%USER%/{{pgrole}}/config:/config'
          - '/opt/seedbox/docker/%USER%/{{pgrole}}/sync:/sync'
          - '/home/%USER%:/home/%USER%'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '%UID%'
          PGID: '%GID%'

    # MAIN DEPLOYMENT #############################################################
    - name: xmlcheck
      stat:
        path: '/opt/seedbox/docker/%USER%/{{pgrole}}/config/config.xml'
      register: xmlcheck

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}-%USER%'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{extport}}:{{intport}}'
          - '{{extport2}}:{{intport2}}'
          - '{{extport3}}:{{intport3}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # ENDING TASK FOR RUTORRENT ####################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: 'Wait 10 Seconds'
          wait_for:
            timeout: 10

        - name: Replace default sync path in config file
          replace:
            path: /opt/seedbox/docker/%USER%/{{pgrole}}/config/config.xml
            regexp: <defaultFolderPath>~</defaultFolderPath>
            replace: '<defaultFolderPath>/sync</defaultFolderPath>'

      when: not xmlcheck.stat.exists
