#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'tautulli'
        intport: '8181'
        image: 'linuxserver/tautulli'

    # CORE (MANDATORY) ############################################################      
    - name: Creating scripts and plugins paths
      file: 'path={{item}} state=directory mode=0775 owner=1000 group=1000'
      with_items:
        - '/opt/seedbox/docker/%USER%/{{pgrole}}/scripts'
        - '/opt/seedbox/docker/%USER%/{{pgrole}}/plugins'

    - name: 'Check if Templates Exist for {{pgrole}}'
      stat:
        path: './templates/{{pgrole}}'
      register: copycheck

    - name: 'Copying Scripts & Plugins'
      copy:
        src: ./templates/{{pgrole}}
        dest: /opt/seedbox/docker/%USER%
        directory_mode: yes
        force: yes
        owner: '%UID%'
        group: '%GID%'
        mode: 0775
      when: copycheck.stat.exists
      
    - name: 'Checking for existing app data'
      stat:
        path: /opt/seedbox/docker/%USER%/tautulli/config.ini
      register: confcheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:plexpy.%DOMAIN%,{{pgrole}}.%DOMAIN%'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/%USER%/{{pgrole}}:/config'
          - '/opt/seedbox/docker/%USER%/plex/database/Library/Application Support/Plex Media Server/Logs:/logs'
          - '/opt/seedbox/docker/%USER%/{{pgrole}}/scripts:/scripts'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '%UID%'
          PGID: '%GID%'
          TZ: 'Europe/Paris'


    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}-%USER%'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # AFTER ########################################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: 'Waiting for {{pgrole}} to start'
          wait_for:
            path: '/opt/seedbox/docker/%USER%/tautulli/config.ini'
            state: present

        - name: Stop Container
          docker_container:
            name: tautulli-%USER%
            state: stopped

        # - name: set http_username
        #   ini_file:
        #     path: '/opt/seedbox/docker/%USER%/{{pgrole}}/config.ini'
        #     section: misc
        #     option: http_username
        #     value: plex
        #     state: present

        # - name: set http_password
        #   ini_file:
        #     path: '/opt/seedbox/docker/%USER%/{{pgrole}}/config.ini'
        #     section: misc
        #     option: http_password
        #     value: guide
        #     state: present

        - name: Restart {{pgrole}}
          docker_container:
            name: '{{pgrole}}-%USER%'
            state: started

      when: not confcheck.stat.exists
