#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: True
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
  
    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: traefik
      when: cloudflare_enabled
      
    - name: Remove Traefik
      docker_container:
        name: traefik
        state: absent

    - name: Create Basic Directories
      file: "path={{item}} state=directory mode=0775 owner=0 group=0"
      with_items:
        - /opt/seedbox/docker/traefik
        - /opt/seedbox/docker/traefik/acme

    - name: Check acme.json exists
      stat:
        path: "/opt/seedbox/docker/traefik/acme/acme.json"
      register: acme_json

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          CF_API_EMAIL: '{{cloudflare.login}}'
          CF_API_KEY: '{{cloudflare.api}}'
      when: cloudflare_enabled

    - name: Installing ACME
      template:
        src: acme.json
        dest: /opt/seedbox/docker/traefik/acme/acme.json
        force: yes
        mode: 0600
        owner: '0'
        group: '0'
      when: acme_json.stat.exists == False

    - name: Installing Traefik.Toml
      template:
        src: traefik.toml
        dest: /opt/seedbox/docker/traefik/traefik.toml
        force: yes
        owner: '0'
        group: '0'
      when: not cloudflare_enabled

    - name: Installing Traefik.Toml
      template:
        src: /opt/seedbox-compose/includes/dockerapps/templates/cloudflare/traefik.toml
        dest: /opt/seedbox/docker/traefik/traefik.toml
        force: yes
        owner: '0'
        group: '0'
      when: cloudflare_enabled

    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '8080'
          traefik.frontend.rule: 'Host:traefik.{{user.domain}}'
          traefik.frontend.auth.basic: '{{ user.htpwd if (not oauth_enabled) | default(false) else omit }}'
          traefik.frontend.headers.SSLHost: 'traefik.{{user.domain}}'
          traefik.docker.network: traefik_proxy
          traefik.frontend.passHostHeader: 'true'
          traefik.frontend.headers.SSLForceHost: 'true'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.forceSTSHeader: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.frameDeny: "false"
          traefik.frontend.auth.forward.address: 'http://oauth:4181'
          traefik.frontend.auth.forward.authResponseHeaders: 'X-Forwarded-User'
          traefik.frontend.auth.forward.trustForwardHeader: 'true'

    # MAIN #########################################################################
    - name: Deploy Traefik
      docker_container:
        name: traefik
        image: traefik:1.7
        pull: yes
        published_ports:
          - "443:443"
          - "80:80"
        command: ["--web", "--accessLog.filePath=/var/log/access.log", "--accessLog.filters.statusCodes=400-499"]
        env: "{{pg_env if cloudflare_enabled == true | default(false) else omit}}"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - /etc/localtime:/etc/localtime:ro
          - /opt/seedbox/docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
          - /opt/seedbox/docker/traefik/acme:/etc/traefik/acme
          - /var/log/traefik:/var/log
        restart_policy: unless-stopped
        state: started
        labels: '{{pg_labels}}'
        networks:
          - name: traefik_proxy

    - name: Google OAuth2 tasks
      include_tasks: 'templates/Google OAuth2/oauth.yml'
      when: oauth_enabled
