#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  tasks:

    # VARIABLES ############################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'
      
    # FACTS #######################################################################

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: ubooquity
      when: cloudflare_config.stat.exists

    - name: Wait for 10 seconds before continuing
      wait_for:
        timeout: 10

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: ubooquityadmin
      when: cloudflare_config.stat.exists

    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ubooquity'
        image: 'zerpex/ubooquity-docker'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.app.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}'
          traefik.app.port: '2202'
          traefik.admin.frontend.rule: 'Host:ubooquityadmin.{{domain.stdout}}'
          traefik.admin.port: '2502'
          traefik.docker.network: 'traefik_proxy'
          traefik.frontend.headers.SSLHost: '{{domain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: 'Setting Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}:/config'
          - '/home/{{user.stdout}}:/home/{{user.stdout}}'
          - '/home/{{user.stdout}}:/media'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting ENV'
      set_fact:
        pg_env:
          UID: '{{userid.stdout}}'
          GID: '{{groupid.stdout}}'
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        hostname: 'library'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'
