---

- set_fact:
    zone_id: "{{ lookup('pipe', 'curl -s -X GET \"https://api.cloudflare.com/client/v4/zones?name=' + user.domain + '\" -H \"X-Auth-Email: ' + cloudflare.login + '\" -H \"X-Auth-Key: ' + cloudflare.api + '\" -H \"Content-Type: application/json\" | jq -r \".result[0].id\"') }}"

- set_fact:
    record_id: "{{ lookup('pipe', 'curl -s -X GET \"https://api.cloudflare.com/client/v4/zones/' + zone_id + '/dns_records?name=' + subdomain + '.' + user.domain + '\" -H \"X-Auth-Email: ' + cloudflare.login + '\" -H \"X-Auth-Key: ' + cloudflare.api + '\" -H \"Content-Type: application/json\" | jq -r \".result[0].id\"') }}"

- command: >
    curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/{{ zone_id }}/dns_records/{{ record_id }}"
    -H "X-Auth-Email: {{ cloudflare.login }}"
    -H "X-Auth-Key: {{ cloudflare.api }}"
    -H "Content-Type: application/json"
  register: delete_result
  
- name: Remove DNS Record
  debug:
    msg: "DNS Record for '{{ subdomain }}' remove from '{{ network.ipv4 }}'."











