
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    - name: Import default config
      template:
        src: /opt/seedbox-compose/includes/config/roles/sasync/templates/sasync.conf.j2
        dest: /opt/sasync/sasync.conf
        mode: 0644

    - name: Import set.file config
      template:
        src: /opt/seedbox-compose/includes/config/roles/sasync/templates/set.file.j2
        dest: /opt/sasync/sets/set.file

    - name: install fclone latest
      shell: |
        wget -P /tmp https://github.com/$(wget https://github.com/mawaya/rclone/releases -O - | egrep '/.*/.*/.*linux-amd64.zip' -o)
        cd /tmp
        archive=$(ls *linux-amd64.zip)
        unzip $archive
        rm $archive
        cd fclone*
        mv fclone /usr/local/bin/fclone
        chmod +x /usr/local/bin/fclone

