---
- hosts: localhost
  gather_facts: true
  vars:
    opened_ports:
      - 80
      - 443
      - 8080
      - 45000
      # Ajoutez les ports nécessaires ici :
      # - 25 # smtp
    allow_ips:
      - 172.17.0.1/12 # réseau docker, ne pas supprimer !
      - 127.0.0.1
      # ajoutez des ip ou des plages supplémentaires ici
      # - 123.456.789.123
      # - fe20:abcd::
  tasks:
    - name: Install UFW
      apt:
        state: present
        name:
          ufw
      ignore_errors: yes
    - name: 'recuperation port ssh'
      debug:
        msg:
          - "{{ ansible_env['SSH_CLIENT'].split() | last }}"
    - name: 'recuperation ip connection'
        debug:
          msg:
            - "{{ ansible_env['SSH_CLIENT'].split() | first }}"

    - name: Enable ufw
      ufw:
        state: enabled
    - name: Open ssh
      ufw:
        rule: allow
        port: "{{ ansible_env['SSH_CLIENT'].split() | last }}"
    - name: Open Current IP
        ufw:
          rule: allow
          from_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"
    - name: Open for authorized IPs
      ufw:
        rule: allow
        from_ip: "{{ item }}"
      loop: "{{ allow_ips }}"
    - name: Apply specific port rules
      ufw:
        rule: allow
        port: "{{ item }}"
      loop: "{{ opened_ports }}"

    - name: Apply plex rules
      ufw:
        name: plexmediaserver-all
        rule: allow
    - name: block all
      ufw:
        policy: reject


