---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: make sure dir is present
      file:
        path: "{{ settings.source }}/tmp"
        state: directory
        owner: "{{ lookup('env','USER') }}"
    - name: make sure file is present
      file:
        path: "{{ item }}"
        state: touch
        owner: "{{ lookup('env','USER') }}"
      with_items:
        - "{{ lookup('env','TMPNAME') }}"
        - "{{ lookup('env','TMPDOMAIN') }}"
        - "{{ lookup('env','TMPGROUP') }}"
    - name: 
      shell: |
        echo {{user.name}} > {{ lookup('env','TMPNAME') }}
        echo {{user.domain}} > {{ lookup('env','TMPDOMAIN') }}
        echo {{user.group}} > {{ lookup('env','TMPGROUP') }}