#########################################################################
# Title:         Cloudbox: System | Locale Tasks                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Locale | Install 'locales'"
  apt:
    name: locales
    state: present

- name: "Locale | Generate 'locales'"
  locale_gen:
    name: "fr_FR.UTF-8"
    state: present
  notify: Handers | Update 'locales'

- name: "Locale | Uncomment '#LANG='"
  replace:
    path: "/etc/default/locale"
    regexp: '^#(LANG=.*)'
    replace: '\1'
  ignore_errors: yes

- name: "Locale | Set Default 'locale'"
  ini_file:
    path: "/etc/default/locale"
    section: null
    option: "LANG"
    value: "fr_FR.UTF-8"
    state: present
    create: yes
    no_extra_spaces: yes
  notify: Handers | Update 'locales'
