#########################################################################
# Title:         Pre-Tasks: Variables Task                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Needed again for cloudbox_mod.

- name: Variables | Check if 'system.timezone' was specified
  set_fact:
    system_timezone_specified: "{{ true if not (
        (system is undefined)
        or
        (system is none)
        or
        (system | trim | length == 0)
        or
        (system.timezone is undefined)
        or
        (system.timezone is none)
        or
        (system.timezone | trim | length == 0)
        or
        (system.timezone | lower == 'auto')
      )
      else false }}"

- name: Variables | Set 'tz' variable to custom timezone
  set_fact:
    tz: "{{ system.timezone }}"
  when: (system_timezone_specified)

- name: Variables | Auto timezone tasks
  block:

  - name: Variables | Get time zone from 'http://ip-api.com'
    uri:
      url: http://ip-api.com/line?fields=timezone
      return_content: yes
    register: ip_api_timezone_response
    ignore_errors: yes

  - name: Variables | Set 'tz' variable from 'http://ip-api.com'
    set_fact:
      tz: "{{ ip_api_timezone_response.content | trim }}"
    when: (ip_api_timezone_response is succeeded)

  - name: Variables | Get timezone from local machine
    block:

    - name: Variables | Check to see if '/etc/timezone' exists
      stat:
        path: /etc/timezone
      register: etc_timezone

    - name: Variables | Set timezone from local machine
      block:

      - name: Variables | Get info from '/etc/timezone'
        shell: cat /etc/timezone
        register: etc_timezone_contents

      - name: Variables | Set 'tz' variable to '/etc/timezone'
        set_fact:
          tz: "{{ etc_timezone_contents.stdout | trim }}"

      when: (etc_timezone.stat.exists and etc_timezone.stat.isreg)

    - name: Variables | Set 'tz' variable to fallback value of 'Etc/UTC'
      set_fact:
        tz: "Etc/UTC"
      when: not (etc_timezone.stat.exists and etc_timezone.stat.isreg)

    when: (ip_api_timezone_response is failed)

  when: (not system_timezone_specified)
