#########################################################################
# Title:         Cloudbox: System Role                                  #
# Author(s):     l3uddz, desimaniac, EnorMOZ                            #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- hosts: localhost
  gather_facts: true
  become: yes

  tasks:

    - name: Set Cloudbox Variables
      import_tasks: "subtasks/variables.yml"
      tags: always

    - name: APT tasks
      include_tasks: "subtasks/apt.yml"

    - name: Network tasks
      import_tasks: "subtasks/network.yml"

    - name: Mounts tasks
      import_tasks: "subtasks/mounts.yml"

    - name: Check if intel_pstate directory exists.
      stat:
        path: /sys/devices/system/cpu/intel_pstate
      register: p

    - name: CPU Frequency tasks
      include_tasks: "subtasks/cpufrequency.yml"
      when: p.stat.isdir is defined and p.stat.isdir

    - name: Remove CPU Power task
      include_tasks: "subtasks/remove_cpupower.yml"

    - meta: flush_handlers

  handlers:
    - name: Handers | Update 'locales'
      command: dpkg-reconfigure --frontend noninteractive locales

    - name: Handers | Update 'tzdata'
      command: dpkg-reconfigure --frontend noninteractive tzdata

