#########################################################################
# Title:         Cloudbox: Plex Patrol Role                             #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- hosts: localhost
  gather_facts: false
  tasks:

    - name: Stop and remove any existing container
      docker_container:
        name: plex_patrol
        state: absent

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{ lookup('env','MYUID') }} group={{ lookup('env','MYGID') }}'
      with_items:
        - '{{ lookup('env','SETTINGS_STORAGE') }}/docker/{{ lookup('env','USER') }}/plex_patrol'

    - name: Check config exists
      stat:
        path: "{{ lookup('env','SETTINGS_STORAGE') }}/docker/{{ lookup('env','USER') }}/plex_patrol/settings.ini"
      register: plex_patrol_config

    - name: Import default config
      template:
        src: "{{ lookup('env','SETTINGS_SOURCE') }}/includes/config/roles/plex_patrol/templates/settings.ini.j2"
        dest: "{{ lookup('env','SETTINGS_STORAGE') }}/docker/{{ lookup('env','USER') }}/plex_patrol/settings.ini"
        owner: "{{ lookup('env','MYUID') }}"
        group: "{{ lookup('env','MYGID') }}"
        mode: 0775
        force: yes
      when: not plex_patrol_config.stat.exists

    - name: 'Set Know Facts'
      set_fact:
        pg_volumes:
          - "{{ lookup('env','SETTINGS_STORAGE') }}/docker/{{ lookup('env','USER') }}/plex_patrol:/config"
          - '/etc/localtime:/etc/localtime:ro'
        pg_env:
          PUID: "{{ lookup('env','MYUID') }}"
          PGID: "{{ lookup('env','MYGID') }}"

    - name: Create and start container
      docker_container:
        name: plex_patrol
        image: "cloudb0x/plex_patrol:latest"
        pull: yes
        env: "{{ pg_env }}"
        volumes: "{{ pg_volumes }}"
        networks:
          - name: traefik_proxy
        purge_networks: yes
        restart_policy: unless-stopped
        state: started
