#########################################################################
# Title:         Cloudbox: Plex Patrol Role                             #
# Author(s):     l3uddz                                                 #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    - name: Stop and remove any existing container
      docker_container:
        name: plex_patrol
        state: absent

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/plex_patrol'

    - name: Check config exists
      stat:
        path: "/opt/seedbox/docker/{{user.name}}/plex_patrol/settings.ini"
      register: plex_patrol_config

    - name: Import default config
      template:
        src: {{ settings.source }}/includes/config/roles/plex_patrol/templates/settings.ini.j2
        dest: /opt/seedbox/docker/{{user.name}}/plex_patrol/settings.ini
        owner: "{{user.userid}}"
        group: "{{user.groupid}}"
        mode: 0775
        force: yes
      when: not plex_patrol_config.stat.exists

    - name: Create and start container
      docker_container:
        name: plex_patrol
        image: "cloudb0x/plex_patrol:latest"
        pull: yes
        user: "{{user.userid}}:{{user.groupid}}"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/seedbox/docker/{{user.name}}/plex_patrol:/config"
        networks:
          - name: traefik_proxy
        purge_networks: yes
        restart_policy: unless-stopped
        state: started
