---

- hosts: localhost
  gather_facts: true
  vars_files:
    - {{ lookup('env','SETTINGS_STORAGE') }}/variables/account.yml
  tasks:

    - name: lauch motd "wazaaaaa"
      import_tasks: "main.yml"

