---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ["{{ lookup('env','CONFDIR') }}/variables/account.yml"]
  tasks:
    - name: Ajout alias
      lineinfile:
        path: "/home/{{ lookup('env','USER') }}/.profile"
        line: "alias seedbox='cd /opt/seedbox-compose && ./seedbox.sh'"

    - name: Ajout chargement venv
      lineinfile:
        path: "/home/{{ lookup('env','USER') }}/.profile"
        line: "cd /opt/seedbox-compose && source profile.sh && cd /home/{{ lookup('env','USER') }}"