#########################################################################
# Title:         Cloudbox: Rclone Role                                  #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- hosts: localhost
  become: yes
  gather_facts: false
  vars_files:
    - 'settings.yml'
    - "{{ lookup('env','HOME') }}/.ansible/inventories/group_vars/all.yml"
  tasks:

    - name: Build URL Tasks
      import_tasks: "build_url.yml"

    - name: Install Binary Tasks
      import_tasks: "install_binary.yml"

    - name: Check if rclone.service exists
      stat:
        path: "/etc/systemd/system/rclone.service"
      register: rclone_service

    - name: Stop rclone service
      systemd:
        name: rclone
        state: stopped
      when: rclone_service.stat.exists

    - name: Create a file
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/rclone/rclone.conf"
        state: touch

    - name: Modify rclone.conf
      blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.config/rclone/rclone.conf"
        block: |
          [zurg]
          type = webdav
          url = http://localhost:9999/dav
          vendor = other
          pacer_min_sleep = 0
          
          [zurghttp]
          type = http
          url = http://localhost:9999/http
          no_head = false
          no_slash = false

    - name: Import systemd rclone.service
      template:
        src: "{{ settings.source }}/includes/config/roles/rclone/templates/rclone.service.j2"
        dest: /etc/systemd/system/rclone.service
        owner: "root"
        group: "root"
        mode: 0775
        force: yes

    - name: Start rclone (Please Wait)
      systemd:
        daemon_reload: yes
        state: started
        name: rclone
        enabled: yes

    - name: Check if rclone is running
      shell: pgrep rclone
      ignore_errors: yes
      changed_when: false
      register: service_rclone_status

    - name: Report status of rclone
      fail:
        msg: |
          - "L'installation de rclone a échoué, Vérifier la configuration du fichier rclone.conf"
      when: service_rclone_status.rc != 0

    - debug:
        msg:
        - "L'installation de rclone s'est déroulée avec succés: Version Rclone {{ rclone_version.stdout }} installée"
        - "Le lancement de rclone s'est effectué avec succés"
      when: service_rclone_status.rc == 0