---
- hosts: localhost
  gather_facts: true
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: 'uninstall exim'
      import_tasks: "subtasks/exim.yml"
      tags: always

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: mail
      when: cloudflare_enabled

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: postfixadmin
      when: cloudflare_enabled

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: spam
      when: cloudflare_enabled

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: webmail
      when: cloudflare_enabled

    - name: 'install mariadb'
      import_tasks: "subtasks/mariadb.yml"
      tags: always

    - name: 'install redis'
      import_tasks: "subtasks/redis.yml"
      tags: always

    - name: 'install mailserver'
      import_tasks: "subtasks/mailserver.yml"
      tags: always

    - name: 'install postfixadmin'
      import_tasks: "subtasks/postfixadmin.yml"
      tags: always

    - name: 'install rainloop'
      import_tasks: "subtasks/rainloop.yml"
      tags: always

    - name: 'install DNS'
      import_tasks: "subtasks/dns.yml"
      tags: always
      when: cloudflare_enabled


