---
- hosts: localhost
  gather_facts: true
  tasks:

    # VARIABLES ############################################################
    - name: 'Register Domain'
      shell: 'cat /opt/seedbox/variables/domain'
      register: domain
      ignore_errors: True

    - name: 'Register user'
      shell: 'cat /opt/seedbox/variables/users'
      register: user
      ignore_errors: True

    - name: 'Register pass'
      shell: 'cat /opt/seedbox/variables/pass'
      register: pass
      ignore_errors: True

    - name: 'uninstall exim'
      import_tasks: "subtasks/exim.yml"
      tags: always

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: mail
      when: cloudflare_config.stat.exists

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: postfixadmin
      when: cloudflare_config.stat.exists

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: spam
      when: cloudflare_config.stat.exists

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: webmail
      when: cloudflare_config.stat.exists

    - name: 'install mariadb'
      import_tasks: "subtasks/mariadb.yml"
      tags: always

    - name: 'install redis'
      import_tasks: "subtasks/redis.yml"
      tags: always

    - name: 'install mailserver'
      import_tasks: "subtasks/mailserver.yml"
      tags: always

    - name: 'install postfixadmin'
      import_tasks: "subtasks/postfixadmin.yml"
      tags: always

    - name: 'install rainloop'
      import_tasks: "subtasks/rainloop.yml"
      tags: always

    - name: 'install DNS'
      import_tasks: "subtasks/dns.yml"
      tags: always
      when: cloudflare_config.stat.exists


