#!/bin/bash
---

- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    - name: 'Import backup config'
      template:
        src: /opt/seedbox-compose/includes/config/roles/backup/templates/backup.j2
        dest: /usr/local/bin/backup
        owner: "root"
        group: "root"
        mode: 0755
        force: yes

    - name: 'Import restore config'
      template:
        src: /opt/seedbox-compose/includes/config/roles/backup/templates/restore.j2
        dest: /usr/local/bin/restore
        owner: "root"
        group: "root"
        mode: 0755
        force: yes

    - name: Set cron
      shell: |
        (crontab -l | grep . ; echo "0 3 * * 6 bash /usr/local/bin/backup > /dev/null") | crontab -
        cp /var/spool/cron/crontabs/root /tmp/root
        sort -u /tmp/root > /var/spool/cron/crontabs/root



