#!/bin/bash
---

- hosts: localhost
  gather_facts: false
  tasks:

    # VARIABLES ############################################################
    - name: 'Register remote'
      shell: 'cat /opt/seedbox/variables/remote'
      register: remote
      ignore_errors: True

    - name: 'Register remoteplex'
      shell: 'cat /opt/seedbox/variables/remoteplex'
      register: remoteplex
      ignore_errors: True

    - name: 'Register user'
      shell: 'cat /opt/seedbox/variables/users'
      register: user
      ignore_errors: True

    - name: 'Register userid'
      shell: 'cat /opt/seedbox/variables/userid'
      register: userid
      ignore_errors: True

    - name: 'Register groupid'
      shell: 'cat /opt/seedbox/variables/groupid'
      register: groupid
      ignore_errors: True

    - name: 'Import backup config'
      template:
        src: /opt/seedbox-compose/includes/config/roles/backup/templates/backup.j2
        dest: /usr/local/bin/backup
        owner: "root"
        group: "root"
        mode: 0755
        force: yes

    - name: 'Import restore config'
      template:
        src: /opt/seedbox-compose/includes/config/roles/backup/templates/restore.j2
        dest: /usr/local/bin/restore
        owner: "root"
        group: "root"
        mode: 0755
        force: yes

    - name: Set cron
      shell: |
        (crontab -l | grep . ; echo "0 3 * * 6 /usr/bin/backup >> /home/{{user.stdout}}/scripts/backup.log") | crontab -


