
---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: group
      prompt: "nom du groupe (sans @googlegroups.com)"
      private: no
    - name: projet
      prompt: "nom du groupe + série de chiffre aléatoire"
      private: no
    - name: prefix
      prompt: "nom du groupe + série de chiffre aléatoire (6 caractères minimum)"
      private: no

  tasks:
    - name: Import default config
      template:
        src: /opt/seedbox-compose/includes/config/roles/gen-sa/templates/sa-gen.j2
        dest: /opt/gen-sa/sa-gen
