
---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: group
      prompt: "nom du groupe créé dans google.group.com"
      private: no

  tasks:
    - name: Import default config
      template:
        src: "{{ settings.source }}/includes/config/roles/safire/templates/default_config.py.j2"
        dest: /opt/safire/safire/default_config.py