#########################################################################
# Title:         UnionFS: Basic Tasks                                   #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

# Variables

- name: "Basics | Check to see if '/mnt/rclone' exists"
  stat:
    path: "/mnt/rclone"
  register: mnt_remote

- name: "Basics | Check to see if '/home/{{ lookup('env','USER') }}/Medias' exists"
  stat:
    path: "/home/{{ lookup('env','USER') }}/Medias"
  register: home_medias

- name: "Basics | Create '/mnt/rclone' directory"
  become: yes
  file: "path=/mnt/rclone state=directory mode=0775 owner={{ lookup('env','USER') }} group={{ lookup('env','MYGID') }} recurse=yes"
  when: (not mnt_remote.stat.exists)

- name: "Basics | Create '/home/{{ lookup('env','USER') }}/Medias' directory"
  become: yes
  file: "path=/mnt/unionfs state=directory mode=0775 owner={{ lookup('env','USER') }} group={{ lookup('env','MYGID') }} recurse=yes"
  when: (not home_medias.stat.exists)