#########################################################################
# Title:         UnionFS: MergerFS Role                                 #
# Author(s):     EnorMOZ, desimaniac                                    #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "MergerFS | Get URL for latest mergerfs release"
  shell: |
    curl -s https://api.github.com/repos/trapexit/mergerfs/releases/latest \
      | jq -r ".assets[] | select(.name | test(\"{{ ansible_distribution|lower }}-{{ ansible_distribution_release|lower }}_amd64\")) \
      | .browser_download_url"
  register: mergerfs_download_url
  ignore_errors: yes

- name: "MergerFS | Set 'mergerfs_download_url_backup' variable"
  set_fact:
    mergerfs_download_url_backup: https://github.com/trapexit/mergerfs/releases/download/2.40.2/mergerfs_2.40.2.{{ ansible_distribution|lower
     }}-{{ ansible_distribution_release|lower }}_amd64.deb

- name: "Create local directory"
  file:
    path: "/home/{{ lookup('env','USER') }}/local"
    state: directory


- name: "MergerFS | Install mergerfs"
  become: yes
  apt:
  
    deb: "{{ mergerfs_download_url.stdout | default('{{ mergerfs_download_url_backup }}') }}"
    state: present

- name: "MergerFS | Import 'mergerfs.service'"
  become: yes
  template:
    src: "{{ settings.source }}/includes/config/roles/unionfs/templates/mergerfs.service.j2"
    dest: /etc/systemd/system/mergerfs.service

- name: "MergerFS | Start 'mergerfs.service'"
  become: yes
  systemd: name=mergerfs.service state=started enabled=yes daemon_reload=yes
