#########################################################################
# Title:         UnionFS: UnionFS Tasks                                 #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "UnionFS | Create unionfs directories"
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.group }} recurse=yes"
  with_items:
    - /home/{{ user.name }}/local/.unionfs-fuse

- name: "UnionFS | Install unionfs"
  apt:
    name: unionfs-fuse
    state: present

- name: "UnionFS | Import 'unionfs.service'"
  template:
    src: "{{ settings.source }}/includes/config/roles/unionfs/templates/unionfs.service.j2"
    dest: /etc/systemd/system/unionfs.service
    force: "{{ 'yes' if ('mounts_override' in ansible_run_tags) else 'no' }}"

- name: "UnionFS | Start 'unionfs.service'"
  systemd: name=unionfs state=started enabled=yes daemon_reload=yes
