---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: set path 
    lineinfile:
      path: "{{ lookup('env','HOME') }}/.bashrc"
      line: "{{ item }}"
  with_items:
  - alias seedbox='{{ settings.source }}/seedbox.sh'