---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:
  - name: Make sure file is present
    file:
      path: "{{ FILE }}"
      state: touch
      owner: "{{ lookup('env','USER') }}"
      group: "{{ lookup('env','MYGIDNAME') }}"