---
- name: Supression du dossier decypharr par precaution s'il existe
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "/home/{{user.name}}/seedbox/docker/{{user.name}}/decypharr"

- name: Check decypharr.service si present
  stat:
    path: /etc/systemd/system/decypharr.service
  register: rclone_status

- name: stop decypharr.service
  become: yes
  systemd:
    name: decypharr
    state: stopped
    enabled: no
  when: rclone_status.stat.exists

- name: suppression decypharr service
  become: yes
  file:
    path: "/etc/systemd/system/decypharr.service"
    state: absent
  when: rclone_status.stat.exists

- name: Create a file
  file:
    path: "{{ lookup('env', 'HOME') }}/.config/rclone/rclone.conf"
    state: touch

- name: Modify rclone.conf
  blockinfile:
    path: "{{ lookup('env', 'HOME') }}/.config/rclone/rclone.conf"
    block: |
      [decypharr]
      type = webdav
      url = http://localhost:8282/webdav/alldebrid
      vendor = other
      pacer_min_sleep = 0

- name: Create service file
  become: yes
  template:
    dest: "/etc/systemd/system/decypharr.service"
    src: "{{ lookup('env', 'SETTINGS_SOURCE') }}/includes/config/roles/rclone/templates/decypharr.service.j2"

- name: Launch rclone
  become: yes
  service:
    daemon-reload: yes
    name: decypharr
    state: started
    enabled: yes

