---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:
  - name: Logrotate
    template:
      src: "{{ lookup('env','BASEDIR') }}/includes/config/playbooks/templates/logrotate.j2"
      dest: /etc/logrotate.d/ansible
      force: yes