---
- hosts: localhost
  gather_facts: false
  roles:
    - kwoodson.yedit
  tasks:
  - name: "Gestion du fichier account.yml - clé {{ account_key }}"
    yedit:
      src: "{{ lookup('env','SETTINGS_STORAGE') }}/variables/account.yml"
      key: "{{ account_key }}"
      value: "{{ account_value }}"
      state: "{{ state }}"