---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Supression du dossier zurg par precaution s'il existe
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      with_items:
      - "/home/{{user.name}}/seedbox/docker/{{user.name}}/zurg"

    - name: Check zurg.service si present
      stat:
        path: /etc/systemd/system/zurg.service
      register: zurg_status

    - name: Stop zurg.service
      become: yes
      systemd:
        name: zurg
        state: stopped
        enabled: no
      when: zurg_status.stat.exists

    - name: suppression zurg service
      become: yes
      file:
        path: "/etc/systemd/system/zurg.service"
        state: absent
      when: zurg_status.stat.exists
 
    - name: Check rclone.service si present
      stat:
        path: /etc/systemd/system/zurg.service
      register: rclone_status

    - name: stop rclone.service
      become: yes
      systemd:
        name: rclone
        state: stopped
        enabled: no
      when: rclone_status.stat.exists

    - name: Generate conf
      template:
        dest: "{{ lookup('env', 'HOME') }}/scripts/zurg/config.yml"
        src: "{{ lookup('env', 'SETTINGS_SOURCE') }}/includes/dockerapps/templates/zurg/config.yml.j2"
        owner: "{{ user.name }}"
        group: "{{ user.groupid }}"

    - name: Create a file
      file:
        path: "{{ lookup('env', 'HOME') }}/.config/rclone/rclone.conf"
        state: touch

    - name: Modify rclone.conf
      blockinfile:
        path: "{{ lookup('env', 'HOME') }}/.config/rclone/rclone.conf"
        block: |
          [zurg]
          type = webdav
          url = http://localhost:9999/dav
          vendor = other
          pacer_min_sleep = 0
          
          [zurghttp]
          type = http
          url = http://localhost:9999/http
          no_head = false
          no_slash = false

    - name: Create directory
      file:
        path: "{{ lookup('env', 'HOME') }}/seedbox/zurg"
        state: directory

    - name: Create service file
      become: yes
      template:
        dest: "/etc/systemd/system/zurg.service"
        src: "{{ lookup('env', 'SETTINGS_SOURCE') }}/includes/config/playbooks/templates/zurg.service.j2"

    - name: Launch zurg
      become: yes
      service:
        daemon-reload: yes
        name: zurg
        state: started
        enabled: yes

