remote_theme: pages-themes/midnight@v0.2.0

plugins:
- jekyll-remote-theme
- jekyll-multiple-languages-plugin
title: SSDv2
description: Simple Seedbox docker

languages: ["fr", "en"]

baseurl: /ssdv2

defaultLang: fr
languageNames:
  fr: Français
  en: English

