---
- hosts: localhost
  gather_facts: true
  vars_files:
    - defaults/main.yml

  tasks:
    - name: 'Register SSH'
      shell: "cat {{ settings.storage }}/variables/ssh"
      register: ssh
      ignore_errors: True

    - name: Run geerlingguy.firewall
      include_role:
        name: geerlingguy.firewall
