---
- hosts: localhost
  gather_facts: true
  become: yes
  tasks:
  - name: Check that group exists
    group:
      name: docker
      state: present
  - name: Add the user to docker group
    user: 
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  - name: Add the user to docker group
    user: 
      name: "{{ lookup('env','SUDO_USER') }}"
      groups: docker
      append: yes
  