#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
############################################################################
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{ lookup('env','CONFDIR') }}/variables/account.yml"
  tasks:

    - name: Install openjdk
      become: yes
      apt:
        name: default-jdk
        state: installed

    # FILEBOT ##############################################################
    - name: Check filebot
      stat:
        path: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/.filebot"
      register: filebot

    - name: Create Basic Directories
      file: "path={{item}} state=directory mode=0775 owner={{user.userid}} group={{lookup('env','MYGID')}}"
      with_items:
        - "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/.filebot"
      when:
        - filebot.stat.exists == False

    - name: Download zsh installer
      get_url: 
        url: https://raw.githubusercontent.com/filebot/plugins/master/installer/tar.sh 
        dest: /tmp/tar.sh
        mode: 0755
      when:
        - filebot.stat.exists == False

    - name: Execute the zsh-installer.sh
      shell: /tmp/tar.sh
      args:
        chdir: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/.filebot"
      when:
        - filebot.stat.exists == False

    - name: Import default filebot-process.sh
      template:
        src: "{{ lookup('env','BASEDIR') }}/includes/config/roles/filebot/templates/filebot-process.sh.j2"
        dest: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/.filebot/filebot-process.sh"
        owner: "{{user.userid}}"
        group: "{{lookup('env','MYGID')}}"
        mode: 0755
        force: yes
      when:
        - filebot.stat.exists == False

    - name: Set filebot.sh as executable
      file:
        path: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/.filebot/filebot.sh"
        owner: "{{ lookup('env','USER') }}"
        group: "{{lookup('env','MYGID')}}"
        mode: a+x
      when:
        - filebot.stat.exists == False

    - name: Set cron
      cron: 
        name: "filebot"
        minute: "*"
        job: "{{ lookup('env','CONFDIR') }}/docker/{{ lookup('env','USER') }}/.filebot/filebot-process.sh > /dev/null"
          

