#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
############################################################################
---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    # FILEBOT ##############################################################
    - name: Check filebot
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/.filebot'
      register: filebot

    - name: Create Basic Directories
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/.filebot'
      when:
        - filebot.stat.exists == False

    - name: Download zsh installer
      get_url: 
        url: https://raw.githubusercontent.com/filebot/plugins/master/installer/tar.sh 
        dest: /tmp/tar.sh
        mode: 0755
      when:
        - filebot.stat.exists == False

    - name: Execute the zsh-installer.sh
      shell: /tmp/tar.sh
      args:
        chdir: /opt/seedbox/docker/{{user.name}}/.filebot
      when:
        - filebot.stat.exists == False

    - name: Import default filebot-process.sh
      template:
        src: /opt/seedbox-compose/includes/config/roles/filebot/templates/filebot-process.sh.j2
        dest: /opt/seedbox/docker/{{user.name}}/.filebot/filebot-process.sh
        owner: "{{user.userid}}"
        group: "{{user.groupid}}"
        mode: 0755
        force: yes
      when:
        - filebot.stat.exists == False

    - name: Set filebot.sh as executable
      file:
        path: /opt/seedbox/docker/{{user.name}}/.filebot/filebot.sh
        owner: "{{user.name}}"
        group: "{{user.groupid}}"
        mode: a+x
      when:
        - filebot.stat.exists == False

    - name: Set update-filebot.sh as executable
      file:
        path: /opt/seedbox/docker/{{user.name}}/.filebot/update-filebot.sh 
        owner: "{{user.name}}"
        group: "{{user.groupid}}"
        mode: a+x
      when:
        - filebot.stat.exists == False

    - name: Set cron
      shell: |
        (crontab -l | grep . ; echo "*/1 * * * * /opt/seedbox/docker/{{user.name}}/.filebot/filebot-process.sh > /dev/null") | crontab -
        cp /var/spool/cron/crontabs/root /tmp/root
        sort -u /tmp/root > /var/spool/cron/crontabs/root
