#########################################################################
# Title:         Cloudbox: Cloudplow Role                               #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---

- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    - name: Check if crop.service exists
      stat:
        path: "/etc/systemd/system/crop_upload.service"
      register: crop_upload_service

    - name: Service Tasks
      block:

      - name: Populate Service Facts
        service_facts:

      - name: stopped Systemd Unit
        systemd:
          name: '{{ item }}.service'
          state: stopped
          enabled: no
        with_items:
          - crop_upload
          - crop_sync

      - name: stopped Systemd Unit
        systemd:
          name: '{{ item }}.timer'
          state: stopped
          enabled: no
        with_items:
          - crop_upload
          - crop_sync

      - name: delete crop folder
        shell: |
          rm /etc/systemd/system/crop_upload.service
          rm /etc/systemd/system/crop_sync.service
          rm /etc/systemd/system/crop_upload.timer
          rm /etc/systemd/system/crop_sync.timer
          rm -rf /home/{{user.name}}/scripts/crop

      when: crop_upload_service.stat.exists

    - name: Check if cloudplow.service exists
      stat:
        path: "/etc/systemd/system/cloudplow.service"
      register: cloudplow_service

    - name: Service Tasks
      block:

      - name: Populate Service Facts
        service_facts:

      - name: Get cloudplow service state
        set_fact:
          cloudplow_service_running: "{{ (services['cloudplow.service'] is defined) and (services['cloudplow.service']['state'] == 'running') }}"

      - name: Stop plex_autoscan service
        systemd:
          name: plex_autoscan
          state: stopped
        when: cloudplow_service_running

      when: cloudplow_service.stat.exists

    - name: Create cloudplow directories
      file: "path={{ item }} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}} recurse=yes"
      with_items:
        - /home/{{user.name}}/scripts/cloudplow

    - name: Clone cloudplow
      git:
        repo: https://github.com/l3uddz/cloudplow/
        dest: /home/{{user.name}}/scripts/cloudplow
        version: HEAD
        force: yes
      become: yes
      become_user: "{{user.name}}"

    - name: Install pip requirements
      pip:
        requirements: /home/{{user.name}}/scripts/cloudplow/requirements.txt
        executable: pip3

    - name: Check config exists
      stat:
        path: "/home/{{user.name}}/scripts/cloudplow/config.json"
      register: cloudplow_config

    - name: Import default config
      template:
        src: /opt/seedbox-compose/includes/config/roles/cloudplow/templates/config.json.j2
        dest: /home/{{user.name}}/scripts/cloudplow/config.json
        owner: "{{user.userid}}"
        group: "{{user.groupid}}"
        mode: 0775
        force: yes
      when: not cloudplow_config.stat.exists

    - name: Set cloudplow.py as executable
      file:
        path: /home/{{user.name}}/scripts/cloudplow/cloudplow.py
        owner: "{{user.userid}}"
        group: "{{user.groupid}}"
        mode: a+x

    - name: Set directory permissions
      file: "path=/home/{{user.name}}/scripts/cloudplow state=directory owner=0 group=0 recurse=yes"

    - name: "Create /usr/local/bin symlink"
      file:
        src: "/home/{{user.name}}/scripts/cloudplow/cloudplow.py"
        dest: "/usr/local/bin/cloudplow"
        state: link

    - name: Import cloudplow service
      template:
        src: /opt/seedbox-compose/includes/config/roles/cloudplow/templates/cloudplow.service.j2
        dest: /etc/systemd/system/cloudplow.service
        force: yes

    - name: Start cloudplow service
      systemd: state=started name=cloudplow daemon_reload=yes enabled=yes
