#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  tasks:

    # VARIABLES ###################################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'

    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'mariadb'
        image: 'mariadb:10.2'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}'

    - name: 'Setting Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.stdout}}/{{pgrole}}:/var/lib/mysql'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting ENV'
      set_fact:
        pg_env:
          MYSQL_ROOT_PASSWORD: 'mysql'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        recreate: true
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started

    # POST DEPLOYMENT ##############################################################

    - name: 'Populate /home/{{user.stdout}}/resume'
      shell: 'echo {{ pgrole }} >> /opt/seedbox/docker/{{user.stdout}}/webserver/resume'

    - name: 'Post Deployment Notes'
      debug:
        msg: |-
          * Login Information * root:mysql * Le mot de passe peut être changé *
