#!/bin/bash

---
- hosts: localhost
  gather_facts: true
  vars_files:
    - /opt/seedbox/variables/account.yml
  vars_prompt:
    - name: sousdomain
      prompt: "Definir le Domaine ou Sous Domaine"
      private: no

    - name: php
      prompt: "php5 ou php7 (Default)->"
      default: "php7"
      private: no

  tasks:

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{ sousdomain }}"
      when: cloudflare_enabled

    - name: Create network
      docker_network:
        name: traefik_proxy
        ipam_options:
          subnet: '172.16.98.0/24'

    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: '{{ sousdomain }}'
        intport: '80'
        image: 'nginx'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/webserver/{{pgrole}}'
        - '/opt/seedbox/docker/{{user.name}}/webserver/{{pgrole}}/config'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.nginx-rtr.entrypoints: 'https'
          traefik.http.routers.nginx-rtr.rule: 'Host(`{{user.domain}}`)'
          traefik.http.routers.nginx-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.nginx-rtr.middlewares: "{{ 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
          ## HTTP Services
          traefik.http.routers.nginx-rtr.service: 'nginx-svc'
          traefik.http.services.nginx-svc.loadbalancer.server.port: '80'

    - name: Import default config
      template:
        src: /opt/seedbox-compose/includes/webserver/app.conf.j2
        dest: /opt/seedbox/docker/{{user.name}}/webserver/{{pgrole}}/config/app.conf
        force: yes

    - name: 'Setting Volumes'
      set_fact:
        pg_volumes:
          - '/var/www/{{pgrole}}:/var/www/{{pgrole}}/app/'
          - '/opt/seedbox/docker/{{user.name}}/webserver/{{pgrole}}/config/app.conf:/etc/nginx/conf.d/app.conf'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    - name: 'Populate /home/{{user.name}}/resume'
      shell: 'echo {{ sousdomain }} >> /opt/seedbox/docker/{{user.name}}/webserver/resume'

    - name: "Install php"
      include_tasks: "/opt/seedbox-compose/includes/webserver/{{ php }}.yml"

