#!/bin/bash

---
- hosts: localhost
  gather_facts: true
  vars_prompt:
    - name: sousdomain
      prompt: "Definir le Domaine ou Sous Domaine"
      private: no

    - name: php
      prompt: "php5 ou php7 (Default)->"
      default: "php7"
      private: no

  tasks:

    # VARIABLES ###################################################################
    - name: 'Including variables'
      include_tasks: '/opt/seedbox-compose/includes/dockerapps/variables.yml'

    - name: Set sousdomain variable
      shell: echo "{{ sousdomain }}" > /opt/seedbox/variables/sousdomain
      when: sousdomain is defined

    - name: 'Register Sous Domaine'
      shell: 'cat /opt/seedbox/variables/sousdomain'
      register: sousdomain
      when: sousdomain is defined

    - name: Set PHP variable
      shell: echo "{{ php }}" > /opt/seedbox/variables/php
      when: sousdomain is defined

    - name: 'Register php'
      shell: 'cat /opt/seedbox/variables/php'
      register: php
      when: sousdomain is defined

    - name: Check config cloudflare exists
      stat:
        path: "/opt/seedbox/variables/cloudflare_api"
      register: cloudflare_config

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{ sousdomain.stdout }}"
      when: cloudflare_config.stat.exists

    - name: Create network
      docker_network:
        name: traefik_proxy
        ipam_options:
          subnet: '172.16.98.0/24'

    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: '{{ sousdomain.stdout }}'
        intport: '80'
        image: 'nginx'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{userid.stdout}} group={{groupid.stdout}}'
      with_items:
        - '/opt/seedbox/docker/{{user.stdout}}/webserver/{{pgrole}}'
        - '/opt/seedbox/docker/{{user.stdout}}/webserver/{{pgrole}}/config'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{sousdomain.stdout}}'
          traefik.frontend.headers.SSLHost: '{{sousdomain.stdout}}'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'

    - name: Import default config
      template:
        src: /opt/seedbox-compose/includes/webserver/app.conf.j2
        dest: /opt/seedbox/docker/{{user.stdout}}/webserver/{{pgrole}}/config/app.conf
        force: yes

    - name: 'Setting Volumes'
      set_fact:
        pg_volumes:
          - '/var/www/{{pgrole}}:/var/www/{{pgrole}}/app/'
          - '/opt/seedbox/docker/{{user.stdout}}/webserver/{{pgrole}}/config/app.conf:/etc/nginx/conf.d/app.conf'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    - name: 'Populate /home/{{user.stdout}}/resume'
      shell: 'echo {{ sousdomain.stdout }} >> /opt/seedbox/docker/{{user.stdout}}/webserver/resume'

    - name: "Install php"
      include_tasks: "/opt/seedbox-compose/includes/webserver/{{ php.stdout }}.yml"

